version: "3"
services:
  my-node-app:
    image: docker-test-react
    container_name: docker-test-react
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
